### ISSUE TITLE
Method missing when following README

### ISSUE THREAD

**Issue by beechnut** [hovancik/middleman-github-deploy#3]
As directed by the README, I ran `gem install mgd` and then `mgd`, to get only this:

```
$ mgd
/Users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fc9e849c75c trollop-2.1.2> (NoMethodError)
        from /Users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
        from /Users/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
        from /Users/user/.rvm/gems/ruby-2.3.1@gemset/gems/mgd-0.1.0/bin/mgd:4:in `<top (required)>'
        from /Users/user/.rvm/gems/ruby-2.3.1@gemset/bin/mgd:23:in `load'
        from /Users/user/.rvm/gems/ruby-2.3.1@gemset/bin/mgd:23:in `<main>'
        from /Users/user/.rvm/gems/ruby-2.3.1@gemset/bin/ruby_executable_hooks:15:in `eval'
        from /Users/user/.rvm/gems/ruby-2.3.1@gemset/bin/ruby_executable_hooks:15:in `<main>'
```

Not sure where to begin in debugging this.

**Comment by hovancik** [comment]
Hi, thanks for the report. 

Can you check what version you have? `gem list | grep mgd`? Also version of ruby? 

There is a problem with v0.1.1 (and I yanked it from rubygems) but v0.1.0 should be fine.

**Comment by hovancik** [comment]
@beechnut seems to be related to this: https://github.com/rubygems/rubygems/issues/1420, please check what is your gem version, should be higher than 2.6.3

```
$ gem --version
```

you can update it via 

```
$ gem update --system  # you might need to be an administrator or root
```
